# Generated by Django 5.0.3 on 2024-03-07 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0003_alter_task_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="tasks", to="task.tag"
            ),
        ),
    ]
